# Generated by Django 3.2.23 on 2024-02-17 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgrOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cfp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=240)),
                ('type', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CfpReqMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=10)),
                ('AGROFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.agroff')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('usertype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=240)),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=10)),
                ('filename', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('photo', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('FARMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReqMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=10)),
                ('FARMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Farmer', to='App.farmer')),
                ('OWNERFARMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OwnerFarmer', to='App.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='TrendNewsTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TechWing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=20)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.login')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=10)),
                ('AGROFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.agroff')),
                ('CFP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.cfp')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReqSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
                ('PRODUCTREQMAIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.productreqmain')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=10)),
                ('FARMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.farmer')),
                ('PRODUCT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.product')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=240)),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=10)),
                ('FARMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.farmer')),
            ],
        ),
        migrations.AddField(
            model_name='farmer',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.login'),
        ),
        migrations.CreateModel(
            name='Doubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=10)),
                ('reply', models.CharField(max_length=100)),
                ('rdate', models.CharField(max_length=15)),
                ('rtime', models.CharField(max_length=10)),
                ('FARMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.farmer')),
                ('TECHWING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.techwing')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_date', models.CharField(max_length=100)),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('reply_date', models.CharField(max_length=100)),
                ('FARMER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=245)),
                ('mdate', models.CharField(max_length=15)),
                ('mtime', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('FARMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.farmer')),
                ('OFFICER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.agroff')),
            ],
        ),
        migrations.CreateModel(
            name='CfpReqSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('CFP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.cfp')),
                ('CFPREQMAIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.cfpreqmain')),
            ],
        ),
        migrations.AddField(
            model_name='cfpreqmain',
            name='FARMER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.farmer'),
        ),
        migrations.CreateModel(
            name='CfpCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=10)),
                ('FARMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.farmer')),
                ('STOCK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.stock')),
            ],
        ),
        migrations.AddField(
            model_name='agroff',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.login'),
        ),
    ]
