# Generated by Django 3.2.23 on 2024-02-18 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20240218_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=100)),
                ('FARMER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.farmer')),
            ],
        ),
        migrations.RemoveField(
            model_name='doubt',
            name='FARMER',
        ),
        migrations.RemoveField(
            model_name='doubt',
            name='TECHWING',
        ),
        migrations.DeleteModel(
            name='MarketPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='FARMER',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='FARMER',
        ),
        migrations.RemoveField(
            model_name='productcart',
            name='PRODUCT',
        ),
        migrations.RemoveField(
            model_name='productreqmain',
            name='FARMER',
        ),
        migrations.RemoveField(
            model_name='productreqmain',
            name='OWNERFARMER',
        ),
        migrations.RemoveField(
            model_name='productreqsub',
            name='PRODUCT',
        ),
        migrations.RemoveField(
            model_name='productreqsub',
            name='PRODUCTREQMAIN',
        ),
        migrations.RemoveField(
            model_name='techwing',
            name='LOGIN',
        ),
        migrations.DeleteModel(
            name='TrendNewsTech',
        ),
        migrations.DeleteModel(
            name='Doubt',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCart',
        ),
        migrations.DeleteModel(
            name='ProductReqMain',
        ),
        migrations.DeleteModel(
            name='ProductReqSub',
        ),
        migrations.DeleteModel(
            name='TechWing',
        ),
    ]
